### ISSUE TITLE
Migrate to RiiConnect24 GitHub

### ISSUE THREAD

**Issue by awesomebing1** [RiiConnect24/RC24-Bot#11]
Per a discussion with @Larsenv, it might be useful to move this to the official GitHub where all the related community can see it, compared to just yours where other communities can see it.

(I'm down for it if you want)

**Comment by Seriell** [comment]
As long as I'm made a member of the RiiConnect24 GitHub, I don't mind ;)

**Comment by larsenv** [comment]
Sent an invitation

**Comment by Seriell** [comment]
Moved.
