### ISSUE TITLE
Roles broken when added to new server

### ISSUE THREAD

**Issue by larsenv** [RiiConnect24/RC24-Bot#34]
RC24 Bot complains when it's added to a new server.

![Complaining](https://puu.sh/wOIHi/7faca72d58.png)

**Comment by spotlightishere** [comment]
This is the same bug as #33, though I'll make this the main thread.

It should just be sufficient to for now set it as you would otherwise: `!config setrole dev <etc>`, despite the names being shortened.

**Comment by spotlightishere** [comment]
This isn't fixed, the underlying issue is still broken. It has something to do with how full_name is passed.
