### ISSUE TITLE
Removing a code incorrectly implies it's a Wii fc

### ISSUE THREAD

**Issue by spotlightishere** [RiiConnect24/RC24-Bot#43]
Running a command such as `!code remove game | <game name>` incorrectly says something such as below:
```
RiiConnect24 Bot BOT - Today at 21:57
:x: A code for Wii <game name> is not registered. 
```

Presumably it would have human readable versions of the name but ¯/\_(ツ)_/¯

**Comment by KcrPL** [comment]
> BTW, i know that it's not a place to do it here but, @spotlightishere please contact me on Discord, we need your help with compiling mailparse.rb to exe

**Comment by spotlightishere** [comment]
Nope, I'm not gonna help you 1 on 1 since that'd prove no help.

Regarding "compiling", Ruby is a parsed language. So you'd need to package an interpreter ter.
https://www.ruby-toolbox.com/categories/packaging_to_executables.html

and uh to "run" mailparse.rb with a custom file, that's pretty easy, won't give help there.

**Comment by KcrPL** [comment]
So is there any way to create Mail Patcher for Windows? We need that because not everyone feels comfortable with joining our Discord server ¯\_(ツ)_/¯

**Comment by spotlightishere** [comment]
did uh I not just post how someone would get around to do that

**Comment by larsenv** [comment]
KcrPL, you have no coue how this works.

**Comment by KcrPL** [comment]
![](http://i.imgur.com/KoNiuuy.gif)

**Comment by KcrPL** [comment]
yea, i don't ¯_(ツ)_/¯

**Comment by spotlightishere** [comment]
Fixed by Java rewrite.
