### ISSUE TITLE
Possible permissions error

### ISSUE THREAD

**Issue by MikeModder** [RiiConnect24/RC24-Bot#51]
!config setchannel gives no permissions error. Looking at BotConfig.java there's no apparent permission checking (I might have missed something in another file) and it allows (seemingly all) users to run !config setchannel.

https://vgy.me/U22rrz.jpg
https://vgy.me/UuAxU4.jpg

**Comment by MikeModder** [comment]
Update: fuck it's really broken

https://vgy.me/5wUHvU

**Comment by ArtutoGamer** [comment]
Can confirm, I removed the command from the public instance

**Comment by MikeModder** [comment]
Yay
