### ISSUE TITLE
!patch not working

### ISSUE THREAD

**Issue by DismissedGuy** [RiiConnect24/RC24-Bot#53]
the bot doesn't reply to uploaded mail files. It doesn't error out or smth, but just doesn't do anything, as seen below:
![image](https://user-images.githubusercontent.com/32306794/32536074-fbc3e2da-c45c-11e7-9e47-e048dd29c11c.png)

**Comment by Seriell** [comment]
Yeah, it doesn't work for me either

**Comment by spotlightishere** [comment]
This appears to be a regression in JDA caused by Java 9. I’ll be recompiling it and upgrading dependencies as needed soon, in the meantime please use Seriel or KcrPL’s patchers.

**Comment by ArtutoGamer** [comment]
Just saying, JDA is not intended to use Java 9.

**Comment by spotlightishere** [comment]
I may have to figure out how to downgrade then. Thanks for letting me know.

**Comment by spotlightishere** [comment]
Fixed in `7de84445dacf511bb6510751bb0f3f9b9207e5ef` because I was too lazy to downgrade.
