### ISSUE TITLE
Auto-role for RC24 Server

### ISSUE THREAD

**Issue by iDroid27210** [RiiConnect24/RC24-Bot#54]
We left few days ago the `Verified` role. Now iBot's auto-role feature adds to each new member the new `Checkpoint` role (that is just an inverted Verified).
We would like to have a second bot to handle the task in the case iBot is down when someone joins.

So, when someone joins the RiiConnect24 server. We wait like 5 seconds, then we check their roles.
If the member has the `Checkpoint` role, it's okay.
If the member doesn't have, we add that role to them. (ID:374627304560656384).

Thank you 👍 
(_Artuto was supposed to do it_)

**Comment by ArtutoGamer** [comment]
>Artuto was supposed to do it

Sorry, but I have a life.

**Comment by spotlightishere** [comment]
this would have to be made modular, as i'd want some way for all servers to implement it (abstraction is cool ok)

**Comment by iDroid27210** [comment]
@ArtutoGamer Yes but it's like 5 lines of code xD A timeout, a check and a addRole thing.

**Comment by spotlightishere** [comment]
if i make this modular, i would want a config to be made with something like this, i'd want an event dedicated to handling, etc. a bit more involved ;p

**Comment by ArtutoGamer** [comment]
Well, since welcome is dead now I'll close this. Reopen if you regret of ripping welcome.
